package com.santander_tc.reglasnegociotc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CardPayment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.santander_tc.reglasnegociotc.model.AmountPayment> amountpayment;
	private java.util.List<com.santander_tc.reglasnegociotc.model.MinimumAmount> minimumamount;

	private java.util.Date operationdate;

	public cardpayment() {
	}

	public java.util.List<com.santander_tc.reglasnegociotc.model.AmountPayment> getAmountpayment() {
		return this.amountpayment;
	}

	public void setAmountpayment(
			java.util.List<com.santander_tc.reglasnegociotc.model.AmountPayment> amountpayment) {
		this.amountpayment = amountpayment;
	}

	public java.util.List<com.santandertc.reglasnegociotc.model.MinimumAmount> getMinimumamount() {
		return this.minimumamount;
	}

	public void setMinimumamount(
			java.util.List<com.santander_tc.reglasnegociotc.model.MinimumAmount> minimumamount) {
		this.minimumamount = minimumamount;
	}

	public java.util.Date getOperationdate() {
		return this.operationdate;
	}

	public void setOperation_date(java.util.Date operationdate) {
		this.operationdate = operationdate;
	}

	public card_payment(
			java.util.List<com.santander_tc.reglasnegociotc.model.amount_payment> amount_payment,
			java.util.List<com.santander_tc.reglasnegociotc.model.minimum_amount> minimum_amount,
			java.util.Date operation_date) {
		this.amountpayment = amount_payment;
		this.minimumamount = minimum_amount;
		this.operationdate = operation_date;
	}

}