package com.santander_tc.reglasnegociotc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Card implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.santander_tc.reglasnegociotc.model.period period;
	private java.lang.String displaynumber;
	private java.lang.String type;
	private java.lang.String status;

	public card() {
	}

	public com.santander_tc.reglasnegociotc.model.period getPeriod() {
		return this.period;
	}

	public void setPeriod(com.santander_tc.reglasnegociotc.model.period period) {
		this.period = period;
	}

	public java.lang.String getDisplaynumber() {
		return this.displaynumber;
	}

	public void setDisplay_number(java.lang.String displaynumber) {
		this.displaynumber = displaynumber;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public card(com.santander_tc.reglasnegociotc.model.period period,
			java.lang.String display_number, java.lang.String type,
			java.lang.String status) {
		this.period = period;
		this.displaynumber = display_number;
		this.type = type;
		this.status = status;
	}

}