package com.santander_tc.reglasnegociotc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Data implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.santander_tc.reglasnegociotc.model.Card Card;

	public data() {
	}

	public com.santander_tc.reglasnegociotc.model.Card getCard() {
		return this.card;
	}

	public void setCard(com.santander_tc.reglasnegociotc.model.Card card) {
		this.card = card;
	}

	public data(com.santander_tc.reglasnegociotc.model.Card card) {
		this.card = card;
	}

}