package com.santander_tc.reglasnegociotc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class period implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.santander_tc.reglasnegociotc.model.period_detail> period_detail;
	private java.lang.String current_period;
	private java.lang.String status;

	public period() {
	}

	public java.util.List<com.santander_tc.reglasnegociotc.model.period_detail> getPeriod_detail() {
		return this.period_detail;
	}

	public void setPeriod_detail(
			java.util.List<com.santander_tc.reglasnegociotc.model.period_detail> period_detail) {
		this.period_detail = period_detail;
	}

	public java.lang.String getCurrent_period() {
		return this.current_period;
	}

	public void setCurrent_period(java.lang.String current_period) {
		this.current_period = current_period;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public period(
			java.util.List<com.santander_tc.reglasnegociotc.model.period_detail> period_detail,
			java.lang.String current_period, java.lang.String status) {
		this.period_detail = period_detail;
		this.current_period = current_period;
		this.status = status;
	}

}