package com.santander_tc.reglasnegociotc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PeriodDetail implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PeriodDetail() {
    }




}