package com.santander_tc.reglasnegociotc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class recurrent_payment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String status;
	private java.util.Date operation_date;

	public recurrent_payment() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.util.Date getOperation_date() {
		return this.operation_date;
	}

	public void setOperation_date(java.util.Date operation_date) {
		this.operation_date = operation_date;
	}

	public recurrent_payment(java.lang.String id, java.lang.String status,
			java.util.Date operation_date) {
		this.id = id;
		this.status = status;
		this.operation_date = operation_date;
	}

}